# CMAKE generated file: DO NOT EDIT!
# Generated by "Unix Makefiles" Generator, CMake Version 2.8

# Default target executed when no arguments are given to make.
default_target: all
.PHONY : default_target

#=============================================================================
# Special targets provided by cmake.

# Disable implicit rules so canonical targets will work.
.SUFFIXES:

# Remove some rules from gmake that .SUFFIXES does not remove.
SUFFIXES =

.SUFFIXES: .hpux_make_needs_suffix_list

# Suppress display of executed commands.
$(VERBOSE).SILENT:

# A target that is always out of date.
cmake_force:
.PHONY : cmake_force

#=============================================================================
# Set environment variables for the build.

# The shell in which to execute make rules.
SHELL = /bin/sh

# The CMake executable.
CMAKE_COMMAND = /usr/bin/cmake

# The command to remove a file.
RM = /usr/bin/cmake -E remove -f

# Escaping for special characters.
EQUALS = =

# The program to use to edit the cache.
CMAKE_EDIT_COMMAND = /usr/bin/ccmake

# The top-level source directory on which CMake was run.
CMAKE_SOURCE_DIR = /home/windos/lyf/WebServer

# The top-level build directory on which CMake was run.
CMAKE_BINARY_DIR = /home/windos/lyf/WebServer

#=============================================================================
# Targets provided globally by CMake.

# Special rule for the target edit_cache
edit_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake cache editor..."
	/usr/bin/ccmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : edit_cache

# Special rule for the target edit_cache
edit_cache/fast: edit_cache
.PHONY : edit_cache/fast

# Special rule for the target rebuild_cache
rebuild_cache:
	@$(CMAKE_COMMAND) -E cmake_echo_color --switch=$(COLOR) --cyan "Running CMake to regenerate build system..."
	/usr/bin/cmake -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR)
.PHONY : rebuild_cache

# Special rule for the target rebuild_cache
rebuild_cache/fast: rebuild_cache
.PHONY : rebuild_cache/fast

# The main all target
all: cmake_check_build_system
	$(CMAKE_COMMAND) -E cmake_progress_start /home/windos/lyf/WebServer/CMakeFiles /home/windos/lyf/WebServer/CMakeFiles/progress.marks
	$(MAKE) -f CMakeFiles/Makefile2 all
	$(CMAKE_COMMAND) -E cmake_progress_start /home/windos/lyf/WebServer/CMakeFiles 0
.PHONY : all

# The main clean target
clean:
	$(MAKE) -f CMakeFiles/Makefile2 clean
.PHONY : clean

# The main clean target
clean/fast: clean
.PHONY : clean/fast

# Prepare targets for installation.
preinstall: all
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall

# Prepare targets for installation.
preinstall/fast:
	$(MAKE) -f CMakeFiles/Makefile2 preinstall
.PHONY : preinstall/fast

# clear depends
depend:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 1
.PHONY : depend

#=============================================================================
# Target rules for targets named WebServer

# Build rule for target.
WebServer: cmake_check_build_system
	$(MAKE) -f CMakeFiles/Makefile2 WebServer
.PHONY : WebServer

# fast build rule for target.
WebServer/fast:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/build
.PHONY : WebServer/fast

src/Signal.o: src/Signal.cpp.o
.PHONY : src/Signal.o

# target to build an object file
src/Signal.cpp.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/Signal.cpp.o
.PHONY : src/Signal.cpp.o

src/Signal.i: src/Signal.cpp.i
.PHONY : src/Signal.i

# target to preprocess a source file
src/Signal.cpp.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/Signal.cpp.i
.PHONY : src/Signal.cpp.i

src/Signal.s: src/Signal.cpp.s
.PHONY : src/Signal.s

# target to generate assembly for a file
src/Signal.cpp.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/Signal.cpp.s
.PHONY : src/Signal.cpp.s

src/Timer.o: src/Timer.cpp.o
.PHONY : src/Timer.o

# target to build an object file
src/Timer.cpp.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/Timer.cpp.o
.PHONY : src/Timer.cpp.o

src/Timer.i: src/Timer.cpp.i
.PHONY : src/Timer.i

# target to preprocess a source file
src/Timer.cpp.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/Timer.cpp.i
.PHONY : src/Timer.cpp.i

src/Timer.s: src/Timer.cpp.s
.PHONY : src/Timer.s

# target to generate assembly for a file
src/Timer.cpp.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/Timer.cpp.s
.PHONY : src/Timer.cpp.s

src/TimerSortList.o: src/TimerSortList.cpp.o
.PHONY : src/TimerSortList.o

# target to build an object file
src/TimerSortList.cpp.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/TimerSortList.cpp.o
.PHONY : src/TimerSortList.cpp.o

src/TimerSortList.i: src/TimerSortList.cpp.i
.PHONY : src/TimerSortList.i

# target to preprocess a source file
src/TimerSortList.cpp.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/TimerSortList.cpp.i
.PHONY : src/TimerSortList.cpp.i

src/TimerSortList.s: src/TimerSortList.cpp.s
.PHONY : src/TimerSortList.s

# target to generate assembly for a file
src/TimerSortList.cpp.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/TimerSortList.cpp.s
.PHONY : src/TimerSortList.cpp.s

src/Utils.o: src/Utils.cpp.o
.PHONY : src/Utils.o

# target to build an object file
src/Utils.cpp.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/Utils.cpp.o
.PHONY : src/Utils.cpp.o

src/Utils.i: src/Utils.cpp.i
.PHONY : src/Utils.i

# target to preprocess a source file
src/Utils.cpp.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/Utils.cpp.i
.PHONY : src/Utils.cpp.i

src/Utils.s: src/Utils.cpp.s
.PHONY : src/Utils.s

# target to generate assembly for a file
src/Utils.cpp.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/Utils.cpp.s
.PHONY : src/Utils.cpp.s

src/config.o: src/config.cpp.o
.PHONY : src/config.o

# target to build an object file
src/config.cpp.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/config.cpp.o
.PHONY : src/config.cpp.o

src/config.i: src/config.cpp.i
.PHONY : src/config.i

# target to preprocess a source file
src/config.cpp.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/config.cpp.i
.PHONY : src/config.cpp.i

src/config.s: src/config.cpp.s
.PHONY : src/config.s

# target to generate assembly for a file
src/config.cpp.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/config.cpp.s
.PHONY : src/config.cpp.s

src/http_conn.o: src/http_conn.cpp.o
.PHONY : src/http_conn.o

# target to build an object file
src/http_conn.cpp.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/http_conn.cpp.o
.PHONY : src/http_conn.cpp.o

src/http_conn.i: src/http_conn.cpp.i
.PHONY : src/http_conn.i

# target to preprocess a source file
src/http_conn.cpp.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/http_conn.cpp.i
.PHONY : src/http_conn.cpp.i

src/http_conn.s: src/http_conn.cpp.s
.PHONY : src/http_conn.s

# target to generate assembly for a file
src/http_conn.cpp.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/http_conn.cpp.s
.PHONY : src/http_conn.cpp.s

src/log.o: src/log.cpp.o
.PHONY : src/log.o

# target to build an object file
src/log.cpp.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/log.cpp.o
.PHONY : src/log.cpp.o

src/log.i: src/log.cpp.i
.PHONY : src/log.i

# target to preprocess a source file
src/log.cpp.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/log.cpp.i
.PHONY : src/log.cpp.i

src/log.s: src/log.cpp.s
.PHONY : src/log.s

# target to generate assembly for a file
src/log.cpp.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/log.cpp.s
.PHONY : src/log.cpp.s

src/main.o: src/main.cpp.o
.PHONY : src/main.o

# target to build an object file
src/main.cpp.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/main.cpp.o
.PHONY : src/main.cpp.o

src/main.i: src/main.cpp.i
.PHONY : src/main.i

# target to preprocess a source file
src/main.cpp.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/main.cpp.i
.PHONY : src/main.cpp.i

src/main.s: src/main.cpp.s
.PHONY : src/main.s

# target to generate assembly for a file
src/main.cpp.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/main.cpp.s
.PHONY : src/main.cpp.s

src/redis_connection_pool.o: src/redis_connection_pool.cpp.o
.PHONY : src/redis_connection_pool.o

# target to build an object file
src/redis_connection_pool.cpp.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/redis_connection_pool.cpp.o
.PHONY : src/redis_connection_pool.cpp.o

src/redis_connection_pool.i: src/redis_connection_pool.cpp.i
.PHONY : src/redis_connection_pool.i

# target to preprocess a source file
src/redis_connection_pool.cpp.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/redis_connection_pool.cpp.i
.PHONY : src/redis_connection_pool.cpp.i

src/redis_connection_pool.s: src/redis_connection_pool.cpp.s
.PHONY : src/redis_connection_pool.s

# target to generate assembly for a file
src/redis_connection_pool.cpp.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/redis_connection_pool.cpp.s
.PHONY : src/redis_connection_pool.cpp.s

src/sql_connection_pool.o: src/sql_connection_pool.cpp.o
.PHONY : src/sql_connection_pool.o

# target to build an object file
src/sql_connection_pool.cpp.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/sql_connection_pool.cpp.o
.PHONY : src/sql_connection_pool.cpp.o

src/sql_connection_pool.i: src/sql_connection_pool.cpp.i
.PHONY : src/sql_connection_pool.i

# target to preprocess a source file
src/sql_connection_pool.cpp.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/sql_connection_pool.cpp.i
.PHONY : src/sql_connection_pool.cpp.i

src/sql_connection_pool.s: src/sql_connection_pool.cpp.s
.PHONY : src/sql_connection_pool.s

# target to generate assembly for a file
src/sql_connection_pool.cpp.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/sql_connection_pool.cpp.s
.PHONY : src/sql_connection_pool.cpp.s

src/webserver.o: src/webserver.cpp.o
.PHONY : src/webserver.o

# target to build an object file
src/webserver.cpp.o:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/webserver.cpp.o
.PHONY : src/webserver.cpp.o

src/webserver.i: src/webserver.cpp.i
.PHONY : src/webserver.i

# target to preprocess a source file
src/webserver.cpp.i:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/webserver.cpp.i
.PHONY : src/webserver.cpp.i

src/webserver.s: src/webserver.cpp.s
.PHONY : src/webserver.s

# target to generate assembly for a file
src/webserver.cpp.s:
	$(MAKE) -f CMakeFiles/WebServer.dir/build.make CMakeFiles/WebServer.dir/src/webserver.cpp.s
.PHONY : src/webserver.cpp.s

# Help Target
help:
	@echo "The following are some of the valid targets for this Makefile:"
	@echo "... all (the default if no target is provided)"
	@echo "... clean"
	@echo "... depend"
	@echo "... WebServer"
	@echo "... edit_cache"
	@echo "... rebuild_cache"
	@echo "... src/Signal.o"
	@echo "... src/Signal.i"
	@echo "... src/Signal.s"
	@echo "... src/Timer.o"
	@echo "... src/Timer.i"
	@echo "... src/Timer.s"
	@echo "... src/TimerSortList.o"
	@echo "... src/TimerSortList.i"
	@echo "... src/TimerSortList.s"
	@echo "... src/Utils.o"
	@echo "... src/Utils.i"
	@echo "... src/Utils.s"
	@echo "... src/config.o"
	@echo "... src/config.i"
	@echo "... src/config.s"
	@echo "... src/http_conn.o"
	@echo "... src/http_conn.i"
	@echo "... src/http_conn.s"
	@echo "... src/log.o"
	@echo "... src/log.i"
	@echo "... src/log.s"
	@echo "... src/main.o"
	@echo "... src/main.i"
	@echo "... src/main.s"
	@echo "... src/redis_connection_pool.o"
	@echo "... src/redis_connection_pool.i"
	@echo "... src/redis_connection_pool.s"
	@echo "... src/sql_connection_pool.o"
	@echo "... src/sql_connection_pool.i"
	@echo "... src/sql_connection_pool.s"
	@echo "... src/webserver.o"
	@echo "... src/webserver.i"
	@echo "... src/webserver.s"
.PHONY : help



#=============================================================================
# Special targets to cleanup operation of make.

# Special rule to run CMake to check the build system integrity.
# No rule that depends on this can have commands that come from listfiles
# because they might be regenerated.
cmake_check_build_system:
	$(CMAKE_COMMAND) -H$(CMAKE_SOURCE_DIR) -B$(CMAKE_BINARY_DIR) --check-build-system CMakeFiles/Makefile.cmake 0
.PHONY : cmake_check_build_system

